### ISSUE TITLE
The serial communication doesn't print whether device is connected or not

### ISSUE THREAD

**Issue by BreadBean** [sparkfun/SparkFun_WM8960_Arduino_Library#5]
I have tried 2 example codes,
1. Example_06_3D_Enhance.ino -- it  only gave me the output " 3D ENHANCE ENABLED" "3D ENHANCE DISABLED"
2. Example_08_I2S_Passthrough.ino -- no output

as per both the code it was supposed to verify whether the connection between wm8960 and esp32 is proper or not  but it didn't print anything

**Comment by lewispg228** [comment]
Hi @BreadBean ,
Sorry you are having an issue here. We're not sure why these two particular examples wouldn't print correctly. We should be able to look further into this later this week. 

Have you been able to see proper start-up serial debug messages with the other examples in the library?

Also, perhaps the terminal connection is not opening soon enough after a reset. It might be worth trying to ensure your com port and serial terminal are open, and then hitting reset button on your ESP32, and then watch for status messages to print on the terminal.

Let us know and thanks,
Pete

**Comment by BreadBean** [comment]
Dear @lewispg228 ,

Thank you for your reply! I’ll try what you suggested next week and see if it resolves the issue.

I also have another question—
**can I use your library to encode the signal from a microphone using the WM8960 codec and then pass it to the ESP32? I noticed there aren't any examples for this specific use case in the library, and I wanted to know if it’s possible.**

Thanks again!

**Comment by BreadBean** [comment]
Hi @lewispg228 ,

I tried what you suggested, and it worked! You were right about the terminal connection not opening soon enough after a reset. Once I ensured that the COM port and serial terminal were open and then pressed the reset button on the ESP32, I was able to see the status messages print on the terminal.

Thanks for the help.
