### ISSUE TITLE
Encoding Microphone Signal with WM8960 and Passing it to ESP32 

### ISSUE THREAD

**Issue by BreadBean** [sparkfun/SparkFun_WM8960_Arduino_Library#6]
Hi, 

Can I use your library to encode the signal from a microphone using the WM8960 codec and then pass it to the ESP32? I noticed there aren't any examples for this specific use case in the library, and I wanted to know if it’s possible.

**Comment by BreadBean** [comment]
@lewispg228 could you help

**Comment by BreadBean** [comment]
??

**Comment by lewispg228** [comment]
Hi @BreadBean , Sorry for the long delay here. Were you able to utilize [Example 08_I2S_Passthrough](https://github.com/sparkfun/SparkFun_WM8960_Arduino_Library/blob/main/examples/Example_08_I2S_Passthrough/Example_08_I2S_Passthrough.ino) and adjust to your use case?

**Comment by BreadBean** [comment]
> Hi @BreadBean , Sorry for the long delay here. Were you able to utilize [Example 08_I2S_Passthrough](https://github.com/sparkfun/SparkFun_WM8960_Arduino_Library/blob/main/examples/Example_08_I2S_Passthrough/Example_08_I2S_Passthrough.ino) and adjust to your use case?

I used the Volume plotter code and serial printed the buffer data.

**Comment by lewispg228** [comment]
Glad you were able to get that going.
