### ISSUE TITLE
Getting an Error in VolumePlotter Example

### ISSUE THREAD

**Issue by BreadBean** [sparkfun/SparkFun_WM8960_Arduino_Library#7]
![image_2024-10-04_093933375](https://github.com/user-attachments/assets/b6e46450-1534-4b06-a331-ad2669d466c4)

**Comment by lewispg228** [comment]
Thanks for letting us know about this error. The I2S driver has been updated, and so the macro we were using (I2S_MCLK_MULTIPLE_DEFAULT) is no longer available to use. Switching to I2S_MCLK_MULTTPLE_512 works. 

Upgrading from the legacy I2S driver is another thing this error brings to light. This may not be necessary for the time being, so going to leave alone for now.

Hope this helps and thanks again!

**Comment by lewispg228** [comment]
Fixed with this commit

https://github.com/sparkfun/SparkFun_WM8960_Arduino_Library/commit/09017d55bd958207b5a6828d198ee29130db2799

Will become live with release v1.0.6
